### ISSUE TITLE
Lower profile for Leonardo case.

### ISSUE THREAD

**Issue by ace-dent** [zygmuntw/3D-Printed-Case-for-Arduino#3]
Hi! Love the design :)
It would be neat if the height of the top lid could be reduced for the Leonardo. The PCB has quite a low profile, except for the power adaptor. Letting this socket poke out, achieves an overall slimmer profile. Like in this more minimal design by Taito: http://www.thingiverse.com/thing:194866.
I tried adjusting the 'height' parameter in your script file but it breaks the cut-outs for the headers, etc... I wondered if you might check the model parameters?

**Comment by zygmuntw** [comment]
Hi, lowered version has been uploaded to Thingiverse http://www.thingiverse.com/thing:628929.

**Comment by ace-dent** [comment]
That looks great! Please could you share the Parameters and updated code on Github for future tinkering? :)
